### ISSUE TITLE
Can you add which TTGO version you are using to the readme, please?

### ISSUE THREAD

**Issue by sxwebster** [bitconnector/ttn_mapper_t-beam#1]
There seems to be differences between TTGO v1.0 and v1.1 that has affected peoples usage in the past. Can you please add a description to the readme showing which version this code has been tested on? Thanks.

**Comment by bitconnector** [comment]
I hope my last commit 6f003903f72a76901bde3ab2ea980dfc463d0e9c solves that confusion
