### ISSUE TITLE
US 915 frequencies? 

### ISSUE THREAD

**Issue by yannickgagne** [bitconnector/ttn_mapper_t-beam#15]
How can I use this code for US LoRa frequencies?

I see a list of freq in lorawan.cpp that are for another region.

Thanks

**Comment by bitconnector** [comment]
Yes
Since I live in europe I am using the EU868 frequencys. In theorie you should be able to easily change the used frequency-list in https://github.com/bitconnector/ttn_mapper_t-beam/blob/b8ba6a38c1f8666df9dffbe859dbe0f3e173d6f7/src/lorawan.cpp#L98

**Comment by yannickgagne** [comment]
I ended up using another repo that gets it's frequencies from LMIC I guess because I didn't need to define them anywhere.

Thanks for the quick reply!
