### ISSUE TITLE
Add readme note regarding which compiler this code was built with 

### ISSUE THREAD

**Issue by sxwebster** [bitconnector/ttn_mapper_t-beam#2]
Although you're using Platform IO via vscode it would be very helpful to note which compiler / debugger you are using. The default platformio compiler cannot deal with comments in the json file and throws an error.

**Comment by bitconnector** [comment]
I havn't tampered with the compiler options in vscode. I'm using the default settings.
Can you tell me why you are getting the error?

**Comment by bitconnector** [comment]
Maybe I've fixed your error. I accidentaly have made a mistake in src/locations.h 40e98ba22a4c30e79e6022c079439dd670f3d714 because obviously I'm using real values and forgot to check if the project is still compiling :|

**Comment by bitconnector** [comment]
If you still have this issue you can reopen this ;)

**Comment by sxwebster** [comment]
Hah, I'll try this over the weekend. Thanks :)
