### ISSUE TITLE
t-beam 1.2 axp2101

### ISSUE THREAD

**Issue by RoZelm0** [bitconnector/ttn_mapper_t-beam#20]
Is it possible to update to this version

https://www.amazon.de/dp/B0B454TB6S?ref=ppx_yo2ov_dt_b_product_details&th=1

**Comment by bitconnector** [comment]
sure :D
you are always welcome to submit a pull request. If you need help just ask me.
Since I don't own this board i can't test changes myself. If you would gift me one, I will write an update ;)

**Comment by RoZelm0** [comment]
Unfortunately I can't create a topic

**Comment by bitconnector** [comment]
No you have to create a fork of this repository.
After that you can make the changes and push them to your repository.
Then you can create a pull request in my repository for the branch in your repository

I will review your changes and apply them if they dont break my code ;)
If you need any further help you can always come back to this thread and ask me

**Comment by RoZelm0** [comment]
what is a fork? I do not understand

**Comment by bitconnector** [comment]
Have you used git before?
What is your expirience writing c code?

**Comment by RoZelm0** [comment]
I only use finished code. I can't write code at all

**Comment by bitconnector** [comment]
Im sorry but I don't think, that you will be able to pull this one off without someone helping you in person.
Maybe I will someday buy this board myself. Then I will update the code. Unfortunately till then it is only compatible with the T-Beam v1.1 with the axp192 power chip.

**Comment by RoZelm0** [comment]
I will be sending this back.
and get cubecell...
I just see you included it

**Comment by bitconnector** [comment]
Its not documented yet, but you just have to select it as target in platformio

This is the board: https://heltec.org/project/htcc-ab02s/

**Comment by maddig21** [comment]
Hi,

i am also stuck with this problem.. There are only send you the V1.2 when you order it.. I tried to implement the new library but i am also not really into coding..

Do you think you can try implement the new library for the new axp2101 and we can test the version?

Thank you

**Comment by bitconnector** [comment]
I can try, but right now I lack the spare time

**Comment by maddig21** [comment]
Ok thank you. I´ve done some research. The new AXP2021 needs a complete new library... I tried to change in the code AXP192 to AXP202 but AXP202 is also a other chip as the new AXP2021. Lilygo uses this library for a sample sketch:

https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/lib/XPowersLib

But as mentioned, my coding skills are not enough to even try, to implement this in this project..

**Comment by maddig21** [comment]
Ich glaube du bist deutsch oder?

Ich könnte dir auch ohne Probleme ein V1.2 zu Verfügung stellen wenn du das willst bzw. benötigst.
Ich frage deswegen, weil ich dein Projekt schon länger auf einem V1.1 benutze und das wirklich gut funktioniert. Nur leider gibt es jetzt nur noch das V1.2...

https://github.com/HrSh3rl0ck/LoRa_APRS_Tracker hier hat jemand mal von der AXP202_ Lib auf die XPowersLib umgebaut. Ist natürlich HAM Stuff aber das Powermanagement ist ja das gleiche.

**Comment by bitconnector** [comment]
Ja
Du kannst mich privat per Telegram anschreiben: https://t.me/lukas_dd

**Comment by bitconnector** [comment]
Schau mal in dein E-Mail Postfach. Da müsste eine Nachricht von diesem Thread gelandet sein

**Comment by bitconnector** [comment]
Ich habe das Update endlich fertig: d26e5dd
Jetzt sollte alles auch mit dem neuen Board laufen ;)
