### ISSUE TITLE
nGPS: no fix\ cubecell_gps

### ISSUE THREAD

**Issue by RoZelm0** [bitconnector/ttn_mapper_t-beam#21]
It always comes ngps_no fix

**Comment by bitconnector** [comment]
Unfortunately this is a quite normal behaviour. The small GPS antenna sometimes takes ages to get a proper fix. Especially for the first time I recommend setting the board outside for a day until it gets a fix

**Comment by bitconnector** [comment]
I would appriciate it if you close this issue, after your error is resolved ;)

**Comment by RoZelm0** [comment]
I forgot to mention that the cubecell just goes out afterwards and gets the CubeCellNot on again. I only get it on USB power off and on again. With Helium github I don't have it and I also have an external one. It is still confusing if I have the cube in the case installation no gps with Helium github.Am 25.09.2023 um 19:41 schrieb bitconnector ***@***.***>:﻿
I would appriciate it if you close this issue, after your error is resolved ;)

**Comment by bitconnector** [comment]
Ich habe gesehen, dass der Link von Amazon.de war. Kannst du mir dein Problem noch einmal auf deutsch schildern?

**Comment by RoZelm0** [comment]
Ich habe vergessen zu erwähnen, dass die Cubecell danach einfach ausgeht und nicht wieder einschaltet. Ich bekomme es nur über USB aus- und wieder an. Mit Helium Github habe ich es nicht und ich habe auch ein externe gps antenne drann. Es ist immer noch verwirrend, wenn ich den Cube im Gehäuse einbaue ist kein gps empfang da mit github vin helium..

**Comment by bitconnector** [comment]
Ich habe an dem Board selbst keine Modifikationen vorgenommen. 
Ich flashe und schließe dann einen Akku an. Allerdings müsste die Stromversorgung auch über USB funktionieren.
Die LED leuchtet erst grün beim joinen und danach rot(dunkel beim schlafen und kurz hell beim senden)
Die Grüne GPS-LED blinkt anfangs kurz und dann regelmäßig, sobald ein fix da ist

Am 20. September 2023 00:44:07 MESZ schrieb RoZelm0 ***@***.***>:

**Comment by RoZelm0** [comment]
Ich kann es jetzt nicht genau sagen wenn ich usb anschliße dann rot und aus.. ich werde das nachher noch mal flashen und testen..

**Comment by bitconnector** [comment]
Kommen regelmäßig Nachrichten über die LoraWan Konsole(TTS/Helium Dashboard) an?

**Comment by RoZelm0** [comment]
nein, wenn es rot leuchtet und aus geht kommen keine Meldung mehr..

**Comment by RoZelm0** [comment]
ich kaufe ein Akku dann versuche ich es noch mal..

**Comment by bitconnector** [comment]
Beim Akku achte am besten auf den Stecker: "1.25 SH 2Pin Premium Mini Micro JST"
Für diesen Stecker ist bereits eine Buchse auf der Rückseite der Platine

**Comment by bitconnector** [comment]
this 9d4694c9589d1a327fb937cdac77b8e0afcc6748 should fix the problem

**Comment by RoZelm0** [comment]
bleibt  hängen bei..

Uploading  ( 90 / 100 )
Uploading  ( 100 / 100 )
Checksum verifies OK.
Rebooting.
Total upload time 12.11s
--- Terminal on COM13 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
GPS current baudrate detecting...
GPS current baudrate detected:115200
GPS baudrate updating...

**Comment by RoZelm0** [comment]
Gesendet von Mail für Windows

Von: bitconnector
Gesendet: Samstag, 30. September 2023 18:52
An: bitconnector/ttn_mapper_t-beam
Cc: RoZelm0; Author
Betreff: Re: [bitconnector/ttn_mapper_t-beam] nGPS: no fix\ cubecell_gps (Issue #21)

this 9d4694c should fix the problem
