### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by djredoo** [bitconnector/ttn_mapper_t-beam#25]
Hi,
thanks for this great project! Very much appreciated!

I'm using a TTGO T-Beam 1.2 with a SSD1306 display.
I just have the issue that the display output is not working for me and I can't figure out how to solve it.
I use your code as is in platform.io and just edited the credentials.
Everything else is working fine.

It would be great if you could help me.
Thanks in advance!

**Comment by bitconnector** [comment]
The Display isnt working, because I only had T-Beams without one so I didnt implement it

I now own one with display and started working on it but I cannot promise any release date

**Comment by djredoo** [comment]
Thanks for your answer. 
Got it. Then I got the wrong impression because of the display.cpp. Reading the code I thought there should at least be some splash screen on start up.
Looking forward for the release with display support!
