### ISSUE TITLE
How to declare the end device in TTS console ?

### ISSUE THREAD

**Issue by vincegre** [bitconnector/ttn_mapper_t-beam#5]
Hi

Thanks for your repo as I plan to use your code for my T-Beam and complete TTNMapper around my area and test also coverage of my own gateway.
How do you declare the T-Beam in End-device creation page in TTS ? Lilygo for sure is not liste, I could find Espressif but it lists only ESPEasy fw and if I go manually it asks a lot of technical details I have no clue what are correct settings for T-Beam :(

Thanks

Vincèn

**Comment by bitconnector** [comment]
If you want to register this device you have to do it manually with the following parameters
![image](https://user-images.githubusercontent.com/34214759/134975985-d0733b6e-4ce1-41a0-84df-aa47ee5cbc53.png)

**Comment by vincegre** [comment]
Thanks for confirmation of proper settings but I'm confused with Lora parameters and how to get them correct between credentials.h file and TTS website !
In credentials the DevEUI is 4 bytes but on TTS it looks to be 8 bytes.
Appskey is AppKey in TTS I guess ? and then Nwkskey is the AppEUI ?

I'll publish on my blog a little tuto once I get everything properly working ;) I'll share you link and feel free to steal all you want in it for your guide :)

**Comment by vincegre** [comment]
Thanks for details I have been able to register it properly in TTN console ;) I'll publish a little guide on my blog once I get everything working properly, I'll share link with you if you want to steal some parts of it for your guide :D

**Comment by bitconnector** [comment]
That would be awesome :D
